-- MySQL Script generated by MySQL Workbench
-- Sat Nov 20 12:19:55 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oc_p5
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `oc_p5` ;

-- -----------------------------------------------------
-- Schema oc_p5
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oc_p5` DEFAULT CHARACTER SET utf8mb4 ;
USE `oc_p5` ;

-- -----------------------------------------------------
-- Table `oc_p5`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oc_p5`.`status` ;

CREATE TABLE IF NOT EXISTS `oc_p5`.`status` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Label` VARCHAR(125) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `oc_p5`.`thematics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oc_p5`.`thematics` ;

CREATE TABLE IF NOT EXISTS `oc_p5`.`thematics` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Label` VARCHAR(125) NULL DEFAULT NULL,
  `Article_count` INT(11) NULL DEFAULT NULL,
  `Slug` VARCHAR(255) NULL DEFAULT NULL,
  `Description` TINYTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `oc_p5`.`article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oc_p5`.`article` ;

CREATE TABLE IF NOT EXISTS `oc_p5`.`article` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Title` TINYTEXT NULL DEFAULT NULL,
  `Exercpt` TINYTEXT NULL DEFAULT NULL,
  `Content` LONGTEXT NULL DEFAULT NULL,
  `Featured_image` VARCHAR(255) NULL DEFAULT NULL,
  `Reading_Time` TINYINT(4) NULL DEFAULT NULL,
  `Slug` VARCHAR(255) NULL DEFAULT NULL,
  `Status` INT(11) NULL DEFAULT NULL,
  `Comment_count` INT(11) NULL DEFAULT NULL,
  `View_count` INT(11) NULL DEFAULT NULL,
  `Created` DATETIME NULL DEFAULT NULL,
  `Modified` DATETIME NULL DEFAULT NULL,
  `Thematics_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Status_article_fk` (`Status` ASC) VISIBLE,
  INDEX `Thematic_Article_fk` (`Thematics_id` ASC) VISIBLE,
  CONSTRAINT `Status_article_fk`
    FOREIGN KEY (`Status`)
    REFERENCES `oc_p5`.`status` (`ID`),
  CONSTRAINT `Thematic_Article_fk`
    FOREIGN KEY (`Thematics_id`)
    REFERENCES `oc_p5`.`thematics` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `oc_p5`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oc_p5`.`comment` ;

CREATE TABLE IF NOT EXISTS `oc_p5`.`comment` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Content` MEDIUMTEXT NULL DEFAULT NULL,
  `Approuved` TINYINT(1) NULL DEFAULT NULL,
  `Created` DATETIME NULL DEFAULT NULL,
  `Modified` DATETIME NULL DEFAULT NULL,
  `Modified_Date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `oc_p5`.`article_comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oc_p5`.`article_comments` ;

CREATE TABLE IF NOT EXISTS `oc_p5`.`article_comments` (
  `Article_id` INT(11) NOT NULL DEFAULT NULL,
  `Comment_Id` INT(11) NULL DEFAULT NULL,
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`),
  INDEX `Article_Id_Article_comment_fk` (`Article_id` ASC) VISIBLE,
  INDEX `Commennt_id_Article_comment_fk` (`Comment_Id` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `Article_Id_Article_comment_fk`
    FOREIGN KEY (`Article_id`)
    REFERENCES `oc_p5`.`article` (`ID`),
  CONSTRAINT `Commennt_id_Article_comment_fk`
    FOREIGN KEY (`Comment_Id`)
    REFERENCES `oc_p5`.`comment` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `oc_p5`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oc_p5`.`tag` ;

CREATE TABLE IF NOT EXISTS `oc_p5`.`tag` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Label` VARCHAR(125) NULL DEFAULT NULL,
  `Article_count` INT(11) NULL DEFAULT NULL,
  `Slug` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `oc_p5`.`article_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oc_p5`.`article_tags` ;

CREATE TABLE IF NOT EXISTS `oc_p5`.`article_tags` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Article_Id` INT(11) NULL DEFAULT NULL,
  `Tag_Id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Article_id_Article_Tags_fk` (`Article_Id` ASC) VISIBLE,
  INDEX `Tag_Article_Tags_fk` (`Tag_Id` ASC) VISIBLE,
  CONSTRAINT `Article_id_Article_Tags_fk`
    FOREIGN KEY (`Article_Id`)
    REFERENCES `oc_p5`.`article` (`ID`),
  CONSTRAINT `Tag_Article_Tags_fk`
    FOREIGN KEY (`Tag_Id`)
    REFERENCES `oc_p5`.`tag` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `oc_p5`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oc_p5`.`role` ;

CREATE TABLE IF NOT EXISTS `oc_p5`.`role` (
  `ID` TINYINT(4) NOT NULL,
  `Label` VARCHAR(125) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `oc_p5`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oc_p5`.`user` ;

CREATE TABLE IF NOT EXISTS `oc_p5`.`user` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `UUID` VARCHAR(36) NOT NULL,
  `Name` VARCHAR(125) NULL DEFAULT NULL,
  `ForName` VARCHAR(125) NULL DEFAULT NULL,
  `Birthday` DATETIME NULL DEFAULT NULL,
  `LastLogin` DATETIME NULL DEFAULT NULL,
  `Avatar` VARCHAR(255) NULL DEFAULT NULL,
  `Role` TINYINT(4) NULL DEFAULT NULL,
  `DisplayName` VARCHAR(125) NULL DEFAULT NULL,
  `Last_activity` DATETIME NULL DEFAULT NULL,
  `Login_Satuts` VARCHAR(50) NULL DEFAULT NULL,
  `Created` DATETIME NULL DEFAULT NULL,
  `Modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID`, `UUID`),
  UNIQUE INDEX `UUID` (`UUID` ASC) VISIBLE,
  INDEX `User_Role_fk` (`Role` ASC) VISIBLE,
  CONSTRAINT `User_Role_fk`
    FOREIGN KEY (`Role`)
    REFERENCES `oc_p5`.`role` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `oc_p5`.`author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oc_p5`.`author` ;

CREATE TABLE IF NOT EXISTS `oc_p5`.`author` (
  `Article_Id` INT(11) NULL DEFAULT NULL,
  `User_UUID` VARCHAR(36) NULL DEFAULT NULL,
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`),
  INDEX `Article_Id_Author_fk` (`Article_Id` ASC) VISIBLE,
  INDEX `User_UUID_Author_fk` (`User_UUID` ASC) VISIBLE,
  CONSTRAINT `Article_Id_Author_fk`
    FOREIGN KEY (`Article_Id`)
    REFERENCES `oc_p5`.`article` (`ID`),
  CONSTRAINT `User_UUID_Author_fk`
    FOREIGN KEY (`User_UUID`)
    REFERENCES `oc_p5`.`user` (`UUID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `oc_p5`.`login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oc_p5`.`login` ;

CREATE TABLE IF NOT EXISTS `oc_p5`.`login` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `User_UUID` VARCHAR(36) NULL DEFAULT NULL,
  `Mail` VARCHAR(125) NULL DEFAULT NULL,
  `Password` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Login_User_fk` (`User_UUID` ASC) VISIBLE,
  CONSTRAINT `Login_User_fk`
    FOREIGN KEY (`User_UUID`)
    REFERENCES `oc_p5`.`user` (`UUID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `oc_p5`.`privilèges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oc_p5`.`privilèges` ;

CREATE TABLE IF NOT EXISTS `oc_p5`.`privilèges` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Action` VARCHAR(125) NULL DEFAULT NULL,
  `Value` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `oc_p5`.`role_privilège`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oc_p5`.`role_privilège` ;

CREATE TABLE IF NOT EXISTS `oc_p5`.`role_privilège` (
  `ID` TINYINT(11) NOT NULL AUTO_INCREMENT,
  `Role_Id` TINYINT(11) NULL DEFAULT NULL,
  `Privileges_Id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Role_Privi_Privi_fk` (`Privileges_Id` ASC) VISIBLE,
  INDEX `Role_Privi_Role_fk` (`Role_Id` ASC) VISIBLE,
  CONSTRAINT `Role_Privi_Privi_fk`
    FOREIGN KEY (`Privileges_Id`)
    REFERENCES `oc_p5`.`privilèges` (`ID`),
  CONSTRAINT `Role_Privi_Role_fk`
    FOREIGN KEY (`Role_Id`)
    REFERENCES `oc_p5`.`role` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `oc_p5`.`user_comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oc_p5`.`user_comments` ;

CREATE TABLE IF NOT EXISTS `oc_p5`.`user_comments` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `User_UUID` VARCHAR(36) NULL DEFAULT NULL,
  `Comment_Id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `Comment_id_Comment_fk`
    FOREIGN KEY (`Comment_Id`)
    REFERENCES `oc_p5`.`comment` (`ID`),
  CONSTRAINT `User_UUID_Comment_fk`
    FOREIGN KEY (`User_UUID`)
    REFERENCES `oc_p5`.`user` (`UUID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `oc_p5`.`timestamps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oc_p5`.`timestamps` ;

CREATE TABLE IF NOT EXISTS `oc_p5`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
